name: voice_example
description: Demonstrates how to use the voice plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_messaging: 10.0.0
  numberpicker: 2.1.1
  path_provider: 2.0.1
  awesome_notifications:
    git:
      url: git://github.com/JoshanTandukar/android.git
  fluttertoast: 8.0.6
  giffy_dialog: ^1.8.0
  flutter_statusbarcolor: ^0.2.3
  url_launcher: ^6.0.3
  progressive_image: 2.0.0
  palette_generator: 0.3.0
  http: 0.13.3
  font_awesome_flutter: 9.0.0
  shared_preferences: 2.0.5
  connectivity: 3.0.3
  flutter_simple_dependency_injection: 2.0.0
  flutter_secure_storage: 4.2.0
  sembast: 3.0.2
  firebase_core: ^1.1.1
#  cloud_firestore: ^0.5.0+1

  voice:
    # When depending on this package from a real application you should use:
    #   voice: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: 0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/placeholder_image.png
    - assets/langs/ar-DZ.json
    - assets/langs/en-US.json
    - assets/langs/hi-IN.json
    - assets/langs/de-DE.json
    - assets/langs/es-ES.json
    - assets/langs/fr-FR.json
    - assets/langs/id-ID.json
    - assets/langs/it-IT.json
    - assets/langs/ja-JP.json
    - assets/langs/ko-KR.json
    - assets/langs/ms-MY.json
    - assets/langs/pt-PT.json
    - assets/langs/ru-RU.json
    - assets/langs/th-TH.json
    - assets/langs/tr-TR.json
    - assets/langs/zh-CN.json
    - assets/images/verify_email_icon.jpg
    - assets/images/baseline_feature_circle_24.png
    - assets/images/baesline_access_time_black_24.png
    - assets/images/baseline_check_green_24.png
    - assets/images/baseline_graph_black_24.png
    - assets/images/baseline_price_down_black_24.png
    - assets/images/baseline_price_up_black_24.png
    - assets/images/empty_basket.png
    - assets/images/empty_fav.png
    - assets/images/fs_android_3x.png
    - assets/images/baseline_percent_tag_orange_24.png
    - assets/images/baseline_empty_item_grey_24.png
    - assets/images/home_icon/discount_products.png
    - assets/images/home_icon/easy_payment.png
    - assets/images/home_icon/featured_products.png
    - assets/images/home_icon/free_download.png
    - assets/images/delivery_car_img.png
    - assets/images/trending.png
    - assets/images/bg-login.png
    - assets/images/textlogo.png
    - assets/images/awesome-notifications-logo-color.png
    - assets/images/awesome-notifications-logo-black.png
    - assets/images/awesome-notifications-logo-white.png
    - assets/images/animated-bell.gif
    - assets/images/placeholder.gif
    - assets/images/happy-dogs.jpg
    - assets/images/balloons-in-sky.jpg
    - assets/images/fireman-hero.jpg
    - assets/images/delivery.jpeg
    - assets/images/melted-clock.png
    - assets/images/rock-disc.jpg
    - assets/images/classic-disc.jpg
    - assets/images/dj-disc.jpg
    - assets/images/80s-disc.jpg
    - assets/images/remix-disc.jpg
    - assets/images/old-disc.jpg
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold-Italic.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
        - asset: assets/fonts/Product-Sans-Italic.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
